// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto

package com.x.y.accumulation.proto.pan;

public interface PanMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PanMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string method = 1;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 1;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>repeated string args = 2;</code>
   */
  java.util.List<java.lang.String>
      getArgsList();
  /**
   * <code>repeated string args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated string args = 2;</code>
   */
  java.lang.String getArgs(int index);
  /**
   * <code>repeated string args = 2;</code>
   */
  com.google.protobuf.ByteString
      getArgsBytes(int index);

  /**
   * <code>repeated .Person persons = 3;</code>
   */
  java.util.List<Person> 
      getPersonsList();
  /**
   * <code>repeated .Person persons = 3;</code>
   */
  Person getPersons(int index);
  /**
   * <code>repeated .Person persons = 3;</code>
   */
  int getPersonsCount();
  /**
   * <code>repeated .Person persons = 3;</code>
   */
  java.util.List<? extends PersonOrBuilder> 
      getPersonsOrBuilderList();
  /**
   * <code>repeated .Person persons = 3;</code>
   */
  PersonOrBuilder getPersonsOrBuilder(
      int index);
}
