// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pandora.proto

package com.x.y.accumulation.proto.pan;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pandora.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bytes audio = 2;</code>
   */
  com.google.protobuf.ByteString getAudio();
}
